### ISSUE TITLE
Can it degrade more gracefully when attempting to embed a video with embedding disabled?

### ISSUE THREAD

**Issue by petehjfd** [solvras/craft-video-toolkit#1]
Hi

When attempting to fetch embed code for a Vimeo video that has embedding disabled, the plugin returns a type error that prevents the entire page from loading.

Obviously we will avoid trying to embed videos with embedding disabled, but in the case where someone forgets to enable embedding, would it be possible for the plugin to degrade more gracefully, i.e. the video just doesn't show rather than killing the entire page?

Thanks

**Comment by johannesSolvr** [comment]
Can you send me a link to the video that is causing problems, so I can test it

**Comment by petehjfd** [comment]
https://vimeo.com/951449793

This video's privacy settings are as follows:

- Hide from Vimeo (Private on your account, but embeddable anywhere)
- Where can the video be embedded? - Nowhere

![Screenshot 2024-05-29 at 10 12 48](https://github.com/solvras/craft-video-toolkit/assets/29060670/35dbb611-e43d-47c6-9634-2d61b9195c3e)

If you attempt to get the video data with oEmbed, you get a 403 Forbidden response - https://vimeo.com/api/oembed.json?url=https://vimeo.com/951449793

So it would be good if the plugin could handle these 403 responses more gracefully.

Thanks

**Comment by johannesSolvr** [comment]
Just released a fix for this issue. Now the video is not showing if oEmbed data isn't available.

**Comment by petehjfd** [comment]
Great, thanks for the quick response
